#include <stdlib.h>

#include "instruction_set.h"

instruction *instructions;

void initialize_instruction_set() {

	instructions = (instruction *)malloc(sizeof(instruction)*
	                                     INSTRUCTIONS_NUMBER);

	
	/* ADC instruction */
	SET_INSTRUCTION_DATA( ADC, MOD, MOD, MOD, NOMOD, NOMOD, MOD );
	SET_INSTRUCTION_ADDR_DATA( ADC, IMMEDIATE, 0x69, 2, 2, NORMAL);
	SET_INSTRUCTION_ADDR_DATA( ADC, ZEROPAGE,  0x65, 2, 3, NORMAL);
	SET_INSTRUCTION_ADDR_DATA( ADC, ZERO_INDX, 0x75, 2, 4, NORMAL);
	SET_INSTRUCTION_ADDR_DATA( ADC, ABSOLUTE,  0x6D, 3, 4, NORMAL);
	SET_INSTRUCTION_ADDR_DATA( ADC, ABS_INDX,  0x7D, 3, 4, NORMAL);
	SET_INSTRUCTION_ADDR_DATA( ADC, ABS_INDY,  0x79, 3, 4, NORMAL);
	SET_INSTRUCTION_ADDR_DATA( ADC, IND_INDIR, 0x61, 2, 6, NORMAL);
	SET_INSTRUCTION_ADDR_DATA( ADC, INDIR_IND, 0x71, 2, 5, NORMAL);

	/* AND instruction */
	SET_INSTRUCTION_DATA( AND, MOD, MOD, NOMOD, NOMOD, NOMOD, NOMOD);
	SET_INSTRUCTION_ADDR_DATA( AND, IMMEDIATE, 0x29, 2, 2, NORMAL);
	SET_INSTRUCTION_ADDR_DATA( AND, ZEROPAGE,  0x25, 2, 3, NORMAL);
   SET_INSTRUCTION_ADDR_DATA( AND, ZERO_INDX, 0x35, 2, 4, NORMAL);
   SET_INSTRUCTION_ADDR_DATA( AND, ABSOLUTE,  0x2D, 3, 4, NORMAL);
   SET_INSTRUCTION_ADDR_DATA( AND, ABS_INDX,  0x3D, 3, 4, PAGE);
   SET_INSTRUCTION_ADDR_DATA( AND, ABS_INDX,  0x39, 3, 4, PAGE);
   SET_INSTRUCTION_ADDR_DATA( AND, IND_INDIR, 0x21, 2, 6, NORMAL);
   SET_INSTRUCTION_ADDR_DATA( AND, INDIR_IND, 0x31, 2, 5, PAGE);

	/* ASL instruction */
	SET_INSTRUCTION_DATA( ASL, MOD, MOD, MOD, NOMOD, NOMOD, NOMOD);
	SET_INSTRUCTION_ADDR_DATA( ASL, ACCUM,     0x0A, 1, 2, NORMAL); 
	SET_INSTRUCTION_ADDR_DATA( ASL, ZEROPAGE,  0x06, 2, 5, NORMAL);
	SET_INSTRUCTION_ADDR_DATA( ASL, ZERO_INDX, 0x16, 2, 6, NORMAL);
	SET_INSTRUCTION_ADDR_DATA( ASL, ABSOLUTE,  0x0E, 3, 6, NORMAL);
	SET_INSTRUCTION_ADDR_DATA( ASL, ABS_INDX,  0x1E, 3, 7, NORMAL);

	/* BCC instruction */
	SET_INSTRUCTION_DATA( BCC, NOMOD, NOMOD, NOMOD, NOMOD, NOMOD, NOMOD);
	SET_INSTRUCTION_ADDR_DATA( BCC, RELATIVE, 0x90, 2, 2, BRANCH);

	/* BCS instruction */
	SET_INSTRUCTION_DATA( BCS, NOMOD, NOMOD, NOMOD, NOMOD, NOMOD, NOMOD);
	SET_INSTRUCTION_ADDR_DATA( BCS, RELATIVE, 0xB0, 2, 2, BRANCH);

	/* BEQ instruction */
	SET_INSTRUCTION_DATA( BEQ, NOMOD, NOMOD, NOMOD, NOMOD, NOMOD, NOMOD);
	SET_INSTRUCTION_ADDR_DATA( BEQ, RELATIVE, 0xF0, 2, 2, BRANCH);

	/* BIT instruction */
	SET_INSTRUCTION_DATA( BIT, M7, MOD, NOMOD, NOMOD, NOMOD, M6);
	SET_INSTRUCTION_ADDR_DATA( BIT, ZEROPAGE, 0x24, 2, 3, NORMAL);
	SET_INSTRUCTION_ADDR_DATA( BIT, ABSOLUTE, 0x2C, 2, 2, NORMAL);

	/* BMI instruction */
	SET_INSTRUCTION_DATA( BMI, NOMOD, NOMOD, NOMOD, NOMOD, NOMOD, NOMOD);
	SET_INSTRUCTION_ADDR_DATA( BMI, RELATIVE, 0x30, 2, 2, BRANCH);

	/* BNE instruction */
	SET_INSTRUCTION_DATA( BNE, NOMOD, NOMOD, NOMOD, NOMOD, NOMOD, NOMOD);
	SET_INSTRUCTION_ADDR_DATA( BNE, RELATIVE, 0xD0, 2, 2, BRANCH);
	
	/* BPL instruction */
	SET_INSTRUCTION_DATA( BPL, NOMOD, NOMOD, NOMOD, NOMOD, NOMOD, NOMOD);
	SET_INSTRUCTION_ADDR_DATA( BPL, RELATIVE, 0x10, 2, 2, BRANCH);

	/* BRK instruction */
	SET_INSTRUCTION_DATA( BRK, NOMOD, NOMOD, NOMOD, 1, NOMOD, NOMOD);
	SET_INSTRUCTION_ADDR_DATA( BPL, IMPLIED, 0x00, 1, 7, NORMAL);

	/* BVC nstruction */
	SET_INSTRUCTION_DATA( BVC, NOMOD, NOMOD, NOMOD, NOMOD, NOMOD, NOMOD);
	SET_INSTRUCTION_ADDR_DATA( BVC, RELATIVE, 0x50, 2, 2, BRANCH);

	/* BVS nstruction */
	SET_INSTRUCTION_DATA( BVS, NOMOD, NOMOD, NOMOD, NOMOD, NOMOD, NOMOD);
	SET_INSTRUCTION_ADDR_DATA( BVS, RELATIVE, 0x70, 2, 2, BRANCH);

	/* CLC instruction */ 
	SET_INSTRUCTION_DATA( CLC, NOMOD, NOMOD, 0, NOMOD, NOMOD, NOMOD);
	SET_INSTRUCTION_ADDR_DATA( CLC, IMPLIED, 0x18, 1, 2, NORMAL);

	return;
}
